### ISSUE TITLE
Boards get lost 

### ISSUE THREAD

**Issue by popanz** [dcaliste/score-board#1] opened 2016-08-25 18:06 UTC
If you start a new board the board gets lost, when you return to the main page. The board gets stored (but not always) when you add some scores. Sometimes you have to restart the phone and suddenly the board reappears.

**Comment by dcaliste** [comment] 2016-08-26 07:33
Thanks for the report, I'll investigate and try to correct this behaviour next week.

**Comment by dcaliste** [comment] 2016-09-01 14:58
May I ask some complement of information ? The fact that a board without any scores are not stored is done by design. The fact that we see quickly a transient entry in the main page that disappears immediately is a flaw in the implementation of that design !

Do you think it would be better to allow to store empty boards ? What would be the use case ?

Second question, may you detail step by step what you're doing to reproduce the board with scores that get lost ? I try to reproduce this behaviour to track the bug, but I cannot. Is it that you have only one row and you are editing a value (the vkb is opened) and you swype back ? In that case, yes the board is deleted.

**Comment by popanz** [comment] 2016-09-01 16:16
Hi Damien,

why to store empty boards:
I play a lot of board games with different game groups (the largest with 8 players). It would be very useful to store empty boards with all the Names of the different players. That would means I don't have to put in the Names of the players for every new game and for every single game group again and again. So for me it would be definitely better to allow the storage of empty boards.  Maybe with the option to clear the scores of a board.

Step by step description:
1. Open Score Board
2. Start an new board
3. Modify the setup
4. choose 5 persons
5 Put in their names
6. Swipe to the board
7. enter for every player a score and swipe to the saved boards.
8. "No stored boards" is displayed

If it helps, I can make a video of that. Maybe you save somewhere debug information and I can send you a log file?

**Comment by dcaliste** [comment] 2016-09-01 18:11
Thanks for the detailled description.

> definitely better to allow the storage of empty boards

Ok, I will change this, so boards with player names and empty score list are stored.

> Maybe with the option to clear the scores of a board.

That should be doable.

In your step by step description, is the virtual keyboard active when you swype back to the saved boards ? If so, I understand the issue and can correct it.

Besides, I've pushed  two commits that allow to:
- tap on player headers to go to the board setup page and edit the name there directly.
- in the board setup page, there is a favorite icon that opens a context menu with the list of all player names already registered.

These should help to set players more quickly. Maybe I should add a way to defined a default board setup also.

**Comment by popanz** [comment] 2016-09-01 18:30
Great! Thank you very much!
Yes the keyboard is active when I swipe back.
Any possibility to donate you or any foss organisation of your choice?

**Comment by dcaliste** [comment] 2016-10-02 19:05
The commit 9fabc4e should solve the issue. I will test it for some days before releasing.
Edit: found some issues, testing a corrected version.

**Comment by popanz** [comment] 2016-10-03 09:19
Hi Damien, that sounds great! I'm really looking forward to test the new version.

**Comment by dcaliste** [comment] 2016-10-04 08:51
Hopefully, it will work as you expect with 1.1.0. I'm closing the bug, but don't hesitate to reopen it if you think it's still broken.

**Closed as completed by dcaliste** 2016-10-04 08:51 UTC
Labels: bug
